### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by itsFrankV22** [Soof4/PvPer#2]
The permissions are wrong, it's not pvper.duel it's pvper.use and it's all broken the plugin makes the player tp backwards all the time even inside the arena

**Comment by LiteralSoofa** [comment]
Oh, yeah i most likely forgot to change the permission... About the other issue, are you sure you've set the arena correctly?

**Comment by itsFrankV22** [comment]
well it's not as explained in the README but I did the best I could, I put the 2 corners of the area then I put the 2 player points and it does tp and damage non-stop

**Comment by LiteralSoofa** [comment]
Hmmm.. Sounds about right, can you send me the content of the ``PvPerConfig.json`` file?

**Comment by itsFrankV22** [comment]
Well I don't have it installed but when I do I'll send you the content of the config

Also if you want I will send you a video of the problem

**Comment by LiteralSoofa** [comment]
Just the config file would be enough for this

**Comment by itsFrankV22** [comment]
Wait, I wasn't at home when I answered, at one point I found out.

**Comment by itsFrankV22** [comment]
Hello again, look at the /duel command, it has the pvper.duel permission, which gives access to the admin commands, which should be separated into another permission. This is also what happens in the video that I provided in the link.


THE VIDEO IS UNLISTED
https://youtu.be/SFMoj-S8rd8

PvPerConfig.json
{
  "README": "/duel set 3 4 Set the coordinates of the player's teleportation higher or lower than the player's coordinates by 3 blocks",
  "README2": "Pull Range: Will retract players from their direction of exiting the arena back to a specified opposite position relative to the arena center (a positive value indicates a position in the same direction). This feature is enabled by default when the option to kill players is disabled.",
  "PermName": "pvper.duel / pvper.admin",
  "PullArena": true,
  "PullRange": -20,
  "PlayerKill": false,
  "PlayerSlap": 100,
  "Player1PositionX": 1951,
  "Player1PositionY": 187,
  "Player2PositionX": 1988,
  "Player2PositionY": 187,
  "ArenaPosX1": 1942,
  "ArenaPosY1": 157,
  "ArenaPosX2": 1996,
  "ArenaPosY2": 190
}

**Comment by LiteralSoofa** [comment]
> it has the pvper.duel permission, which gives access to the admin commands, which should be separated into another permission.
Yeah, I'll fix that tomorrow.

I've seen the video, arena definition is correct. it seems like something is wrong with checking if the player is in arena, I'll also look into this tomorrow.

Thank you so much for providing the details, that helps a lot. <3

**Comment by itsFrankV22** [comment]
Thank you, it is a pleasure to collaborate to improve, I thank you for responding so quickly.

**Comment by LiteralSoofa** [comment]
This has been fixed in [v1.1.3](https://github.com/Soof4/PvPer/releases/tag/v1.1.3). Please check it out and report if it works as expected!
